// Exception handling

try {
    console.log("hello");

    console.log(x);
} catch (e) {
    console.log("some error occurred");
} finally {
    console.log("i am always printed");
}

console.log("welcome");

/*
Such instances can be called as exceptions / error in your code

when your code has bugs

or it doesnt work the way you want


exception handling is used for code where we 
feel that error may occur

-- network calls - - Api calls

*/
